-- Create all tables needed for Horizontal Flight Efficiency
--
-- Prerequisites: create_type.sql
-- 

CREATE GLOBAL TEMPORARY TABLE HFE_TMP_BLOCKS_MEASURED
(
   BLOCK_NAME       VARCHAR2 (8 CHAR) NOT NULL
,  GK_MES_AREA_ID   INTEGER NOT NULL
)
ON COMMIT DELETE ROWS;

CREATE UNIQUE INDEX HFE_TMP_BLOCKS_MEASURED_UNQ
   ON HFE_TMP_BLOCKS_MEASURED (BLOCK_NAME
,                                      GK_MES_AREA_ID
);

/*****************/


CREATE TABLE HFE_AREA_DEFINITIONS
(
   gk_id        INTEGER NOT NULL PRIMARY KEY
,  BLOCK_type   VARCHAR2 (5 CHAR) NOT NULL
,  members      area_group
)
NESTED TABLE members
   STORE AS hfe_area_groups_table;

INSERT INTO HFE_AREA_DEFINITIONS (gk_id, block_type)
     VALUES (0, 'ANY');

/*****************/

CREATE TABLE HFE_LOG
(
   MSG_TIME   TIMESTAMP
,  MESSAGE    VARCHAR2 (1000 CHAR)
);

/*****************/

CREATE TABLE HFE_FLIGHTS
(
   GK_REF_AREA_ID          INTEGER NOT NULL
,  SAM_ID                  INTEGER NOT NULL
,  MODEL_TYPE              VARCHAR2 (5 CHAR) NOT NULL
,  STATUS                  INTEGER NOT NULL
,  ADEP                    VARCHAR2 (5 CHAR) NOT NULL
,  ADES                    VARCHAR2 (5 CHAR) NOT NULL
,  APT_GCD_DIST_KM         NUMBER NOT NULL
,  TRAJ_LENGTH_KM          NUMBER NOT NULL
,  OD_GCD_DIST_KM          NUMBER NOT NULL
,  ADEP_TIME               DATE NOT NULL
,  DTMA40_TIME             DATE NOT NULL
,  ATMA40_TIME             DATE NOT NULL
,  ADES_TIME               DATE NOT NULL
,  ORIGIN_TYPE             CHAR (3 CHAR) NOT NULL
,  ORIGIN_LOC              VARCHAR2 (8 CHAR) NOT NULL
,  ORIGIN_TIME             DATE NOT NULL
,  ORIGIN_DIST_KM          INTEGER NOT NULL
,  ORIGIN_LAT              NUMBER NOT NULL
,  ORIGIN_LON              NUMBER NOT NULL
,  DESTINATION_TYPE        CHAR (3 CHAR) NOT NULL
,  DESTINATION_LOC         VARCHAR2 (8 CHAR) NOT NULL
,  DESTINATION_TIME        DATE NOT NULL
,  DESTINATION_DIST_KM     INTEGER NOT NULL
,  DESTINATION_LAT         NUMBER NOT NULL
,  DESTINATION_LON         NUMBER NOT NULL
,  ENROUTE_START_TYPE      CHAR (3 CHAR) NOT NULL
,  ENROUTE_START_LOC       VARCHAR2 (8 CHAR) NOT NULL
,  ENROUTE_START_TIME      DATE NOT NULL
,  ENROUTE_START_DIST_KM   INTEGER NOT NULL
,  ENROUTE_START_LAT       NUMBER NOT NULL
,  ENROUTE_START_LON       NUMBER NOT NULL
,  ENROUTE_END_TYPE        CHAR (3 CHAR) NOT NULL
,  ENROUTE_END_LOC         VARCHAR2 (8 CHAR) NOT NULL
,  ENROUTE_END_TIME        DATE NOT NULL
,  ENROUTE_END_DIST_KM     INTEGER NOT NULL
,  ENROUTE_END_LAT         NUMBER NOT NULL
,  ENROUTE_END_LON         NUMBER NOT NULL
,  LAST_TOUCHED            DATE NOT NULL
,  HFE_PKG_VERSION         NUMBER NOT NULL
,  CONSTRAINT HFE_FLIGHTS_FK_REF FOREIGN KEY
      (GK_REF_AREA_ID)
       REFERENCES HFE_AREA_DEFINITIONS (GK_ID)
)
PARTITION BY RANGE
   (SAM_ID)
   INTERVAL (50000)
      (PARTITION P_DEF
         VALUES LESS THAN
            (143100000));

CREATE UNIQUE INDEX HFE_FLIGHTS_PK
   ON HFE_FLIGHTS (SAM_ID, MODEL_TYPE, GK_REF_AREA_ID)
;

ALTER TABLE HFE_FLIGHTS ADD (
  CONSTRAINT HFE_FLIGHTS_PK
 PRIMARY KEY
(SAM_ID, MODEL_TYPE, GK_REF_AREA_ID)
     USING INDEX HFE_FLIGHTS_PK
);


/*****************/

CREATE TABLE HFE_SPACES
(
   GK_REF_AREA_ID       INTEGER NOT NULL
,  SAM_ID               INTEGER NOT NULL
,  MODEL_TYPE           VARCHAR2 (5 CHAR) NOT NULL
,  GK_MES_AREA_ID       INTEGER NOT NULL
,  ENTRY_NB             INTEGER NOT NULL
,  NX_FLOWN_KM          INTEGER NOT NULL
,  NX_DIRECT_KM         NUMBER NOT NULL
,  NX_ACHIEVED_KM       NUMBER NOT NULL
,  ENTRY_TIME           DATE NOT NULL
,  ENTRY_DIST_KM        INTEGER NOT NULL
,  ENTRY_LAT            NUMBER NOT NULL
,  ENTRY_LON            NUMBER NOT NULL
,  EXIT_TIME            DATE NOT NULL
,  EXIT_DIST_KM         INTEGER NOT NULL
,  EXIT_LAT             NUMBER NOT NULL
,  EXIT_LON             NUMBER NOT NULL
,  LAST_TOUCHED         DATE NOT NULL
,  HFE_PKG_VERSION         NUMBER NOT NULL
,  CONSTRAINT HFE_SPACES_DIST CHECK (EXIT_DIST_KM >= ENTRY_DIST_KM)
,  CONSTRAINT HFE_SPACES_TIME CHECK (EXIT_TIME >= ENTRY_TIME)
,  CONSTRAINT HFE_SPACES_FK_REF FOREIGN KEY
      (SAM_ID, MODEL_TYPE, GK_REF_AREA_ID)
      REFERENCES HFE_FLIGHTS (SAM_ID, MODEL_TYPE, GK_REF_AREA_ID)
,  CONSTRAINT HFE_SPACES_FK_MES FOREIGN KEY
      (GK_MES_AREA_ID)
       REFERENCES HFE_AREA_DEFINITIONS (GK_ID)
)
PARTITION BY RANGE
   (ENTRY_TIME)
   INTERVAL ( NUMTODSINTERVAL (1, 'DAY') )
   (
      PARTITION P_DEF
         VALUES LESS THAN
            (TO_DATE ('2010-12-31 00:00:00'
,                     'SYYYY-MM-DD HH24:MI:SS'
,                     'NLS_CALENDAR=GREGORIAN')));

CREATE UNIQUE INDEX HFE_SPACES_PK
   ON HFE_SPACES (ENTRY_TIME
,                             MODEL_TYPE
,                             GK_REF_AREA_ID
,                             GK_MES_AREA_ID
,                             SAM_ID
,                             ENTRY_NB)
   LOCAL;

ALTER TABLE HFE_SPACES ADD (
  CONSTRAINT HFE_SPACES_PK
 PRIMARY KEY
(ENTRY_TIME, MODEL_TYPE, GK_REF_AREA_ID, GK_MES_AREA_ID, SAM_ID, ENTRY_NB)
    USING INDEX HFE_SPACES_PK
);