DROP TABLE HFE_TMP_BLOCKS_MEASURED CASCADE CONSTRAINTS PURGE;
ALTER TABLE HFE_AREA_DEFINITIONS DROP COLUMN members;
DROP TABLE HFE_AREA_DEFINITIONS CASCADE CONSTRAINTS PURGE;
DROP TABLE HFE_LOG PURGE;
DROP TABLE HFE_SPACES  CASCADE CONSTRAINTS PURGE;
DROP TABLE HFE_FLIGHTS CASCADE CONSTRAINTS PURGE;
DELETE SPERRORLOG WHERE USERNAME=(SELECT SYS_CONTEXT ('USERENV', 'SESSION_USER') FROM DUAL);